[workspace]
members = [
  "agents/orchestrator",
  "agents/ingestion",
  "agents/retrieval",
  "agents/critic",
  "agents/telemetry",
  "agents/planner-adapter",
  "src-tauri",
  "rust-backend",
]
resolver = "2"
