---
ignoredBuiltDependencies:
  - optipng-bin
  - pngquant-bin
  - sharp
  - zopflipng-bin

onlyBuiltDependencies:
  - core-js
  - esbuild
  - optipng-bin
  - pngquant-bin
  - sharp
  - tauri
  - zopflipng-bin

overrides:
  npm@<5.7.1: '>=5.7.1'
  npm@<6.14.6: '>=6.14.6'
  npm@<6.13.4: '>=6.13.4'
  npm@<6.13.3: '>=6.13.3'

packages:
  - stack-ui
  - src-tauri
  - agents/*
  - rust-backend
  - docs
