---
name: Link Checker (mdBook)

permissions:
  contents: read

on:
  push:
    paths:
      - 'docs/**'

jobs:
  mdbook-linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install mdBook-linkcheck
        run: cargo install mdbook-linkcheck
      - name: Run mdBook-linkcheck
        run: mdbook-linkcheck docs/src
