---
name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
