---
name: Lint Docs (Vale)

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Vale
        run: |
          curl -fsSL https://install.goreleaser.com/github.com/errata-ai/vale.sh \
            | sh
          sudo mv ./bin/vale /usr/local/bin/vale
      - name: Run Vale
        run: |
          vale --version
          vale .
